export const EMPTY_MOVIE = {
  adult: false,
  backdrop_path: '',
  id: 0,
  original_language: '',
  original_title: '',
  overview: '',
  popularity: 0,
  poster_path: '',
  release_date: '',
  title: '',
  video: false,
  vote_average: 0,
  vote_count: 0,
};

export const EMPTY_MOVIE_DETAIL = {
  adult: false,
  backdrop_path: '',
  belongs_to_collection: {
    id: 0,
    name: '',
    poster_path: '',
    backdrop_path: '',
  },
  budget: 0,
  genres: [],
  homepage: '',
  id: 0,
  imdb_id: '',
  original_language: '',
  original_title: '',
  overview: '',
  popularity: 0,
  poster_path: '',
  production_companies: [],
  production_countries: [],
  release_date: '',
  revenue: 0,
  runtime: 0,
  spoken_languages: [],
  status: '',
  tagline: '',
  title: '',
  video: false,
  vote_average: 0,
  vote_count: 0,
};
